version: '3.9'

services:
  postgres:
    image: postgres:17-alpine3.20
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      # POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./ddl.sql:/ddl.sql
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    # entrypoint: ["/bin/sh", "/docker-entrypoint-initdb.d/init.sh"]

  bun:
    image: oven/bun:alpine
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    command: ["sh", "-c", "bun install && bun test"]
    restart: "no"

volumes:
  pgdata: